/**
 * types.ts
 * ---------------------------------------------------------------------------
 * The single source of truth for every contract that crosses a boundary:
 *   extension  <-> backend        (HTTP + SSE)
 *   backend    <-> LLM providers  (normalised internally)
 *
 * Phase 5 requirement: the frontend must never be able to tell which model
 * produced a response. Everything below is therefore provider-agnostic; the
 * only place a provider name appears is the informational `meta` event.
 * ---------------------------------------------------------------------------
 */

/* =========================================================================
 * 1. Providers
 * ========================================================================= */

/** Ordered identifiers for the fallback waterfall. */
export type ProviderId = 'anthropic' | 'gemini' | 'openai';

/** Human-facing label used in the `meta` SSE event. */
export interface ProviderInfo {
  provider: ProviderId;
  model: string;
}

/* =========================================================================
 * 2. Canonical conversation format
 *
 * Every provider adapter converts *from* this shape into its own wire format.
 * Nothing provider-specific ever leaks into the session store.
 * ========================================================================= */

/** A tool the model decided to invoke. `id` is generated by us if a provider
 *  (Gemini) does not supply one. */
export interface CanonToolCall {
  id: string;
  name: string;
  /** Already-parsed arguments. Never a JSON string. */
  arguments: Record<string, unknown>;
  /**
   * Gemini 3+ attaches an opaque signature to every functionCall part and
   * rejects the whole request (HTTP 400) if the history is replayed without
   * it. Stored here verbatim; other providers ignore it.
   */
  thoughtSignature?: string;
}

export interface CanonUserMessage {
  role: 'user';
  content: string;
}

export interface CanonAssistantMessage {
  role: 'assistant';
  /** May be empty when the model replied with tool calls only. */
  content: string;
  toolCalls: CanonToolCall[];
}

export interface CanonToolMessage {
  role: 'tool';
  toolCallId: string;
  name: string;
  /** Raw JSON returned by the extension, or a normalised error envelope. */
  result: unknown;
}

export type CanonMessage =
  | CanonUserMessage
  | CanonAssistantMessage
  | CanonToolMessage;

/* =========================================================================
 * 3. Tool definitions
 * ========================================================================= */

/** A minimal JSON-Schema subset that all three providers accept. */
export interface JsonSchema {
  type: 'object';
  properties: Record<string, JsonSchemaProperty>;
  required?: string[];
  additionalProperties?: boolean;
  description?: string;
}

export interface JsonSchemaProperty {
  type: 'string' | 'number' | 'integer' | 'boolean' | 'array' | 'object';
  description?: string;
  enum?: string[];
  items?: JsonSchemaProperty;
  properties?: Record<string, JsonSchemaProperty>;
  required?: string[];
  /** Stripped before being sent to Gemini, which rejects unknown keys. */
  default?: unknown;
  additionalProperties?: boolean;
}

export interface ToolDefinition {
  /** Must match a key in the extension's AbhiBusAPIRegistry.handlers map,
   *  unless `serverSide` is true — then the gateway executes it itself. */
  name: string;
  description: string;
  parameters: JsonSchema;
  /** True when the endpoint requires a logged-in AbhiBus session. */
  requiresAuth: boolean;
  /** True when the gateway runs this tool locally (see serverTools.ts)
   *  instead of round-tripping to the extension. */
  serverSide?: boolean;
}

/* =========================================================================
 * 4. HTTP request / response bodies
 * ========================================================================= */

/** POST /api/chat — opens the SSE stream. */
export interface ChatRequestBody {
  /** Stable per browser tab. Used to correlate the tool-result callback. */
  sessionId: string;
  message: string;
  /** Prior turns, oldest first. Trimmed server-side to MAX_HISTORY. */
  history?: ChatHistoryTurn[];
  /** Optional page context (current URL, detected route) for grounding. */
  pageContext?: PageContext;
}

export interface ChatHistoryTurn {
  role: 'user' | 'assistant';
  content: string;
}

export interface PageContext {
  url?: string;
  /** e.g. "bus_search", "account/trips" — helps the model pick defaults. */
  path?: string;
  /** ISO date the user is currently browsing, if detectable. */
  journeyDate?: string;
}

/** POST /api/tool-result — the extension answering a `tool_call` event. */
export interface ToolResultBody {
  sessionId: string;
  toolCallId: string;
  /** Present on success. */
  result?: unknown;
  /** Present on failure. `UNAUTHENTICATED` is handled specially. */
  error?: ToolExecutionError;
}

export interface ToolExecutionError {
  code: 'UNAUTHENTICATED' | 'NETWORK' | 'HTTP_ERROR' | 'UNKNOWN_TOOL' | 'TIMEOUT' | 'UNKNOWN';
  message: string;
  status?: number;
}

export interface ApiErrorResponse {
  ok: false;
  code: string;
  message: string;
}

export interface ApiOkResponse {
  ok: true;
}

/* =========================================================================
 * 5. Normalised SSE event envelope
 *
 * Every event is written as:   event: <type>\ndata: <json>\n\n
 * The extension switches on `type` only — never on provider.
 * ========================================================================= */

export type SseEventType =
  | 'meta'
  | 'status'
  | 'text_delta'
  | 'tool_call'
  | 'tool_result_ack'
  | 'server_tool'
  | 'error'
  | 'done';

/** Emitted once per provider attempt, before any text. */
export interface SseMetaEvent {
  type: 'meta';
  sessionId: string;
  provider: ProviderId;
  model: string;
  /** 1 = primary, 2 = first fallback, 3 = second fallback. */
  attempt: number;
}

/** Drives the shimmer / typing indicator in the Shadow DOM panel. */
export interface SseStatusEvent {
  type: 'status';
  state:
    | 'connecting'
    | 'thinking'
    | 'calling_tool'
    | 'awaiting_tool_result'
    | 'switching_provider'
    | 'finalising';
  detail?: string;
}

export interface SseTextDeltaEvent {
  type: 'text_delta';
  text: string;
}

/** Backend pauses here and waits for POST /api/tool-result. */
export interface SseToolCallEvent {
  type: 'tool_call';
  toolCallId: string;
  name: string;
  arguments: Record<string, unknown>;
  /** Milliseconds after which the backend gives up waiting. */
  timeoutMs: number;
}

export interface SseToolResultAckEvent {
  type: 'tool_result_ack';
  toolCallId: string;
  ok: boolean;
}

/** Display-only: a tool the gateway executed itself (no extension round trip).
 *  The panel shows the same activity chip it shows for extension tools. */
export interface SseServerToolEvent {
  type: 'server_tool';
  name: string;
  state: 'running' | 'done' | 'failed';
  detail?: string;
}

export interface SseErrorEvent {
  type: 'error';
  code:
    | 'ALL_PROVIDERS_FAILED'
    | 'UNAUTHENTICATED'
    | 'TOOL_TIMEOUT'
    | 'RATE_LIMITED'
    | 'BAD_REQUEST'
    | 'INTERNAL';
  message: string;
  /** True when the UI should show the "Click here to Log In" affordance. */
  requiresLogin?: boolean;
}

export interface SseDoneEvent {
  type: 'done';
  finishReason: 'stop' | 'tool_loop_exhausted' | 'error' | 'aborted';
  provider?: ProviderId;
  /** Round-trip wall time in ms, for the debug footer. */
  elapsedMs: number;
}

export type SseEvent =
  | SseMetaEvent
  | SseStatusEvent
  | SseTextDeltaEvent
  | SseToolCallEvent
  | SseToolResultAckEvent
  | SseServerToolEvent
  | SseErrorEvent
  | SseDoneEvent;

/* =========================================================================
 * 6. Provider adapter contract
 * ========================================================================= */

/** What a single streaming turn yields back to the orchestrator. */
export interface ProviderTurnResult {
  /** Concatenated assistant text emitted during this turn. */
  text: string;
  /** Tool calls the model wants executed before it can continue. */
  toolCalls: CanonToolCall[];
  finishReason: 'stop' | 'tool_use' | 'length' | 'unknown';
}

/** Callbacks the orchestrator hands to an adapter. */
export interface ProviderStreamHooks {
  onTextDelta(text: string): void;
  /** Called the moment the first byte of *any* content arrives, so the
   *  orchestrator knows the response is "committed" and can no longer
   *  silently fall back to another provider. */
  onCommit(): void;
}

export interface ProviderRequest {
  system: string;
  messages: CanonMessage[];
  tools: ToolDefinition[];
  /** 'none' forbids tool calls — used for the forced final-answer turn after
   *  the tool budget is exhausted. Defaults to 'auto'. */
  toolChoice?: 'auto' | 'none';
  maxTokens: number;
  temperature: number;
  signal: AbortSignal;
}

export interface ProviderAdapter {
  readonly id: ProviderId;
  readonly model: string;
  /** True only when the required API key is configured. */
  isConfigured(): boolean;
  stream(req: ProviderRequest, hooks: ProviderStreamHooks): Promise<ProviderTurnResult>;
}
